spring:
  profiles:
    active: dev

logging:
  level:
    #ROOT: DEBUG
    org.springframework.web: DEBUG
    com.jorgerivera: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /var/log/application.log